/*
 * Copyright (c) 2026 tutosrive. All rights reserved.
 *
 * Author: tutosrive
 * GitHub: https://github.com/tutosrive
 *
 * This source code is PROPRIETARY and CONFIDENTIAL.
 * Unauthorized copying, modification, or distribution of this file,
 * via any medium, is strictly prohibited.
 *
 * This software is provided "as is", without warranty of any kind.
 * In no event shall the author be liable for any claim or damages.
 */

package com.srm.scrollbar_fastscroll_v1;

import java.util.ArrayList;

public record TestData() {
    public static ArrayList<String> getData() {
        ArrayList<String> data = new ArrayList<>();
        data.add("Nihil blanditiis et enim doloribus pariatur facilis.");
        data.add("Aliquam est quia.");
        data.add("Dolore praesentium iste nulla occaecati.");
        data.add("Maxime natus occaecati sed tempore hic non dolores officiis dolore.");
        data.add("Est voluptates neque sequi veritatis aliquam.");
        data.add("Dolorum ut ut ut aut.");
        data.add("Enim quas labore sit.");
        data.add("Consequatur quasi corporis sapiente laborum et deleniti ducimus eos aut.");
        data.add("Debitis quis a praesentium et quisquam.");
        data.add("Excepturi laborum exercitationem quam corporis maxime voluptas non.");
        data.add("Quas inventore sapiente in expedita.");
        data.add("Sed rerum laudantium quo autem distinctio mollitia.");
        data.add("Id mollitia quibusdam non tempora.");
        data.add("Est sed perspiciatis.");
        data.add("A sed ullam.");
        data.add("Eum laboriosam sunt maiores fugiat sed.");
        data.add("Officia debitis aut.");
        data.add("Corrupti qui sapiente quia enim exercitationem.");
        data.add("Consequatur molestiae laboriosam accusantium numquam tempore.");
        data.add("Dolores nisi aut non.");
        data.add("Qui saepe porro est.");
        data.add("Libero repudiandae dicta sunt molestiae iste.");
        data.add("Placeat vero omnis aliquid beatae asperiores.");
        data.add("Est quibusdam repudiandae omnis vero.");
        data.add("Veniam nostrum reprehenderit.");
        data.add("Labore sequi laudantium incidunt.");
        data.add("Consequuntur fugiat modi ratione perferendis cum molestias quidem.");
        data.add("Totam est eum.");
        data.add("Dolores id qui officiis nulla et.");
        data.add("Omnis consequatur commodi asperiores delectus placeat.");
        data.add("Natus et sint harum et.");
        data.add("Delectus quos modi nemo id.");
        data.add("Ut illo dolor aut et qui non.");
        data.add("Tempore enim soluta aut praesentium dolorem ipsa qui consequatur soluta.");
        data.add("Illo praesentium veniam corporis tempora eveniet aperiam odit.");
        data.add("Quos rerum voluptatibus facilis nulla quasi qui deserunt.");
        data.add("Perferendis officia in eum quisquam atque molestiae est error.");
        data.add("Officia dignissimos omnis enim.");
        data.add("Animi rerum qui pariatur voluptatem recusandae harum.");
        data.add("Adipisci porro est eos aspernatur nesciunt.");
        data.add("Sunt fuga possimus perspiciatis.");
        data.add("Culpa labore a delectus.");
        data.add("Assumenda perspiciatis perferendis.");
        data.add("Aliquid minus enim sint.");
        data.add("Cum saepe sapiente ipsa rerum qui doloremque.");
        data.add("Et corrupti in consequatur sed qui quia rerum aut.");
        data.add("Voluptatem pariatur delectus.");
        data.add("Pariatur consequatur eum voluptate rerum non dolor quis.");
        data.add("Sit qui ipsum dolores ut cum cupiditate.");
        data.add("Beatae velit laborum animi.");
        data.add("Reiciendis aut molestias omnis.");
        data.add("Aspernatur autem eos quidem quidem debitis et.");
        data.add("Non praesentium voluptas voluptas expedita est mollitia.");
        data.add("Ipsum saepe reiciendis quam.");
        data.add("Eveniet repudiandae maxime id.");
        data.add("Vitae ea et quos nisi omnis temporibus est illum.");
        data.add("Id qui consectetur similique quo.");
        data.add("Et a magni exercitationem.");
        data.add("Cum non qui atque quis inventore aut doloremque id.");
        data.add("Perspiciatis id nulla.");
        data.add("Modi voluptas officiis in vitae sit cupiditate est.");
        data.add("Quod dolor omnis rerum illum qui quidem ut.");
        data.add("Quasi omnis nesciunt beatae minus qui deserunt nisi nesciunt.");
        data.add("Est molestias quaerat omnis molestiae non non.");
        data.add("Possimus pariatur qui numquam magni.");
        data.add("Id in quaerat laboriosam ea veniam ut.");
        data.add("Similique consequatur et maiores.");
        data.add("Aliquam qui consequatur mollitia delectus ut.");
        data.add("Aut magni quidem sapiente ex quasi quia.");
        data.add("Modi error alias suscipit ipsa voluptatum tenetur.");
        data.add("Blanditiis voluptatibus dolorem placeat ea mollitia nam quaerat architecto libero.");
        data.add("Et possimus voluptas.");
        data.add("Ea reiciendis et est nihil qui assumenda.");
        data.add("Et dolorum nesciunt.");
        data.add("Dolorem quia voluptas perspiciatis fuga eos exercitationem sint.");
        data.add("Cum reiciendis est totam nostrum sed consequuntur.");
        data.add("Doloribus inventore explicabo fugiat tenetur dolores nostrum veniam.");
        data.add("Veritatis ipsa quas natus iste numquam et quis voluptatem rerum.");
        data.add("Voluptates et accusantium repellendus et voluptatem.");
        data.add("Facere qui voluptas id et ab error omnis.");
        data.add("Enim soluta accusantium iure repudiandae omnis et sunt laboriosam est.");
        data.add("Aperiam mollitia eius.");
        data.add("Ut deleniti totam quo vel aut ea.");
        data.add("Eligendi consectetur velit reprehenderit quia.");
        data.add("Enim doloremque ut cum molestiae quia corporis et veritatis.");
        data.add("Dignissimos iste a perferendis fugit.");
        data.add("Sit nostrum mollitia quis quo.");
        data.add("Aut asperiores eos sed nulla praesentium minus voluptas.");
        data.add("Excepturi aut eos facere eos.");
        data.add("Sed et et necessitatibus.");
        data.add("Voluptatem non dolores optio.");
        data.add("Quas placeat aut suscipit repellat saepe.");
        data.add("Enim saepe alias deserunt.");
        data.add("At neque quod.");
        data.add("Suscipit qui fuga sunt maiores.");
        data.add("Consequatur officia facere.");
        data.add("In blanditiis eum sed recusandae autem accusantium necessitatibus aut.");
        data.add("Saepe sit vero.");
        data.add("Unde et minus eum possimus corporis nostrum.");
        data.add("Laboriosam ipsum debitis reprehenderit tempora.");
        data.add("Atque quae cum sit omnis consequatur et.");
        data.add("Omnis voluptate veniam iure aspernatur quia.");
        data.add("Architecto doloremque eos sed voluptas et voluptatibus.");
        data.add("Recusandae laborum quo.");
        data.add("Quaerat est aut facere nostrum sit totam molestiae fugit ratione.");
        data.add("Voluptatem quia officiis et.");
        data.add("Et laudantium pariatur facere quam porro dolorem.");
        data.add("In ipsum error sit ut.");
        data.add("Ea veniam veniam harum voluptatem dolore aut ut.");
        data.add("Architecto commodi omnis quia expedita earum.");
        data.add("Non aliquid magnam eos consequuntur.");
        data.add("Sit officia maxime enim rerum vel.");
        data.add("Quidem hic nulla voluptatum architecto sint facilis hic.");
        data.add("Voluptatum ea error corporis temporibus tenetur molestiae nostrum in.");
        data.add("Tempora molestiae et eveniet quia dicta non et.");
        data.add("Dolor rerum quis molestiae aut aspernatur commodi velit inventore aliquid.");
        data.add("Eius sint odit sit vitae placeat ut sint.");
        data.add("Accusamus sint provident sed debitis.");
        data.add("Eum tempora aut sed impedit neque facilis praesentium vel.");
        data.add("Eos odio ipsam nulla cumque et quisquam quod.");
        data.add("Maiores omnis vel labore dolorem.");
        data.add("Ea dignissimos placeat voluptatem et porro voluptas.");
        data.add("Voluptate eaque consequatur autem veniam pariatur quas.");
        data.add("Dolores nemo non omnis quasi dolores sequi.");
        data.add("Aliquid aut rerum sequi earum.");
        data.add("Vitae totam quia facere voluptatem.");
        data.add("Delectus vero quaerat dolorum aut a est.");
        data.add("Illum commodi repudiandae voluptatum eos.");
        data.add("Consequatur corrupti consectetur.");
        data.add("Ea inventore voluptas.");
        data.add("Repudiandae unde numquam at optio atque aut ipsum.");
        data.add("In ipsam explicabo nihil aut numquam dicta eum aut cupiditate.");
        data.add("Qui magnam quis facere vel consectetur nobis.");
        data.add("Ut aut autem magnam ea harum assumenda.");
        data.add("Pariatur et porro unde officiis quod quo.");
        data.add("Fuga voluptatibus id qui.");
        data.add("Molestias reprehenderit laudantium voluptas.");
        data.add("Eos et vitae officiis alias reiciendis hic nostrum esse et.");
        data.add("Voluptas ut cumque nostrum aut.");
        data.add("Nihil magni eligendi maiores.");
        data.add("Dolor officiis molestiae ea ut est repellat.");
        data.add("Et quidem quia quia aliquid quia.");
        data.add("Aut aspernatur harum ut.");
        data.add("Soluta facere debitis quod soluta facilis.");
        data.add("Et nisi fugiat autem dolor et qui culpa aspernatur.");
        data.add("Veritatis omnis recusandae qui quisquam incidunt eligendi ex illo.");
        data.add("Ut omnis accusamus.");
        data.add("Maiores et aut ex consequuntur sed esse magni eos.");
        data.add("Accusantium fuga sint.");
        data.add("Rerum quibusdam aut eum sunt.");
        data.add("Omnis eligendi aut.");
        data.add("Iste amet id et ratione cumque laboriosam deserunt repellat consequatur.");
        data.add("Deserunt ea et atque sit molestiae.");
        data.add("Voluptates est ut enim unde perferendis eum laboriosam eos autem.");
        data.add("Dignissimos fuga quia quia numquam vero ad omnis cumque.");
        data.add("Et ut repudiandae.");
        data.add("Similique eaque sed ipsam ut repellat dolorum tempora.");
        data.add("Est corrupti recusandae necessitatibus reiciendis non.");
        data.add("A est ut labore placeat similique.");
        data.add("Sapiente sunt beatae quod blanditiis animi.");
        data.add("Dolorem sed voluptas porro molestiae.");
        data.add("Natus at sint et labore occaecati explicabo accusamus.");
        data.add("Reprehenderit qui ipsa impedit.");
        data.add("Asperiores voluptates sunt quos illo impedit veritatis.");
        data.add("Sunt iste iste voluptates quis facere earum et unde soluta.");
        data.add("Nobis non omnis minus voluptas mollitia consequuntur qui est eum.");
        data.add("Eum vel dolores et sed.");
        data.add("Libero sint rem.");
        data.add("Culpa sed voluptatibus vitae voluptatem.");
        data.add("Perspiciatis libero vel libero sapiente molestiae.");
        data.add("Consectetur perspiciatis minus expedita assumenda.");
        data.add("Impedit eveniet officiis minima.");
        data.add("Consequatur ut nulla autem quod similique optio.");
        data.add("Iure quas ipsam pariatur.");
        data.add("Modi est cumque possimus dolore animi aut.");
        data.add("Quaerat impedit velit quam minus corporis sunt quos.");
        data.add("Nam sint qui praesentium ullam.");
        data.add("Eum saepe sapiente est inventore quidem ullam tenetur.");
        data.add("Veritatis perspiciatis tempora assumenda accusantium qui.");
        data.add("Hic non consequatur.");
        data.add("Minima recusandae nam culpa.");
        data.add("Sit dolores sequi cupiditate tempore eius aut velit odit tempora.");
        data.add("Ullam molestias perferendis officiis atque.");
        data.add("Nihil eum nostrum rerum sunt ea quos et quia voluptatibus.");
        data.add("Enim reiciendis nihil ut dolor ad animi nostrum.");
        data.add("Error adipisci accusamus culpa voluptatibus qui.");
        data.add("Doloremque voluptatem voluptatem quam doloribus voluptas dolore error culpa numquam.");
        data.add("Sit mollitia et iste officia aspernatur et accusantium.");
        data.add("Aliquid dolore ut.");
        data.add("Minima magnam ut pariatur porro deleniti consectetur.");
        data.add("Ratione enim ducimus.");
        data.add("Quibusdam minima pariatur ut consequuntur et aspernatur praesentium.");
        data.add("Assumenda eos quo rem optio eius ad omnis autem.");
        data.add("Perspiciatis reiciendis omnis possimus temporibus nisi expedita dolores.");
        data.add("Necessitatibus molestias repudiandae autem ea.");
        data.add("Minima facere aut totam atque dicta est voluptatem illum neque.");
        data.add("Ipsum perferendis aspernatur rerum dolorum in consequuntur voluptatum quia magni.");
        data.add("Iusto possimus et excepturi sequi quia non nostrum animi.");
        data.add("Exercitationem ab natus similique.");
        data.add("Harum quia quia.");
        return data;
    }
}
